const Termsofuse = () => {
  return (
    <>
      <div className="TermsofUse">
        <center>
          <h1> Terms of Use</h1>
        </center>
        <hr />
        <p>
          <b>Disclaimer:</b> In case of any discrepancy or difference, the
          English version will take precedence over the translation
        </p>
        <p>
          This document is an electronic record in terms of Information
          Technology Act, 2000 and rules there under as applicable and the
          amended provisions pertaining to electronic records in various
          statutes as amended by the Information Technology Act, 2000. This
          electronic record is generated by a computer system and does not
          require any physical or digital signatures.
        </p>
        <p>
          This document is published in accordance with the provisions of Rule 3
          (1) of the Information Technology (Intermediaries guidelines) Rules,
          2011 that require publishing the rules and regulations, privacy policy
          and Terms of Use for access or usage of domain name
          \[www.electromart.com\] (“Website”), including the related mobile site
          and mobile application (hereinafter referred to as “Platform”)
        </p>
        <p>
          The Platform is owned by electromart Internet Private Limited, a
          company incorporated under the Companies Act, 1956 with its registered
          office at Buildings Alyssa, Begonia & Clover, Embassy Tech Village,
          Outer Ring Road, Devarabeesanahalli Village, Bengaluru – 560103,
          Karnataka, India and its branch offices at 2nd Floor, Block F (Flora),
          Embassy Tech Village, Outer Ring Road, Devarabeesanahalli Village,
          Bengaluru-560103, Karnataka, India and; 447/C, 12th Main, 4th Block,
          Koramangala, Bengaluru-560034, Karnataka, India (hereinafter referred
          to as "electromart").
        </p>
        <p>
          our use of the Platform and services and tools are governed by the
          following terms and conditions ("Terms of Use") as applicable to the
          Platform including the applicable policies which are incorporated
          herein by way of reference. If You transact on the Platform, You shall
          be subject to the policies that are applicable to the Platform for
          such transaction. By mere use of the Platform, You shall be
          contracting with electromart Internet Private Limited and these terms
          and conditions including the policies constitute Your binding
          obligations, with electromart.
        </p>
        <p>
          For the purpose of these Terms of Use, wherever the context so
          requires "You" or "User" shall mean any natural or legal person who
          has agreed to become a buyer on the Platform by providing Registration
          Data while registering on the Platform as Registered User using the
          computer systems. electromart allows the User to surf the Platform or
          making purchases without registering on the Platform. The term "We",
          "Us", "Our" shall mean electromart Internet Private Limited.
        </p>
        <p>
          ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR
          AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO
          PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly
          or expressly accepting these Terms of Use, You also accept and agree
          to be bound by electromart Policies ((including but not limited to
          Privacy Policy available at Privacy) as amended from time to time.
        </p>
        <h6>Membership Eligibility</h6>
        <p>
          Transaction on the Platform is available only to persons who can form
          legally binding contracts under Indian Contract Act, 1872. Persons who
          are "incompetent to contract" within the meaning of the Indian
          Contract Act, 1872 including un-discharged insolvents etc. are not
          eligible to use the Platform. If you are a minor i.e. under the age of
          18 years, you may use the Platform or access content on the Platform
          only under the supervision and prior consent/ permission of a parent
          or legal guardian.
        </p>
        <p>
          As a minor if you wish to transact on the Platform, such transaction
          on the Platform may be made by your legal guardian or parents.
          electromart reserves the right to terminate your membership and / or
          refuse to provide you with access to the Platform if it is brought to
          electromart's notice or if it is discovered that You are under the age
          of 18 years and transacting on the Platform.
        </p>
        <h6>Your Account and Registration Obligations</h6>
        <p>
          If You use the Platform, You shall be responsible for maintaining the
          confidentiality of your Display Name and Password and You shall be
          responsible for all activities that occur under your Display Name and
          Password. You agree that if You provide any information that is
          untrue, inaccurate, not current or incomplete or We have reasonable
          grounds to suspect that such information is untrue, inaccurate, not
          current or incomplete, or not in accordance with the this Terms of
          Use, We shall have the right to indefinitely suspend or terminate or
          block access of your membership on the Platform and refuse to provide
          You with access to the Platform.
        </p>
        <p>
          Your mobile phone number and/or e-mail address is treated as Your
          primary identifier on the Platform. It is your responsibility to
          ensure that Your mobile phone number and your email address is up to
          date on the Platform at all times. You agree to notify Us promptly if
          your mobile phone number or e-mail address changes by updating the
          same on the Platform through a onetime password verification.
        </p>
        <p>
          You agree that electromart shall not be liable or responsible for the
          activities or consequences of use or misuse of any information that
          occurs under your Account in cases, including, where You have failed
          to update Your revised mobile phone number and/or e-mail address on
          the Website Platform.
        </p>
        <p>
          If You share or allow others to have access to Your account on the
          Platform (“Account”), by creating separate profiles under Your
          Account, or otherwise, they will be able to view and access Your
          Account information. You shall be solely liable and responsible for
          all the activities undertaken under Your Account, and any consequences
          there from.
        </p>
        <p>
          You must maintain confidentiality of the account information and for
          all the activities that occur under Your account. You must not share
          your login details, ie, username and password of Your account with any
          other person, else it would be considered breach of this Terms of Use.
        </p>
        <p>
          You agree to: (a) ensure that You successfully log out from Your
          account at the end of each session; and (b) immediately notify
          electromart of any unauthorized use of Your account. If there is
          reason to believe that there is likely to be a breach of security or
          misuse of Your account, We may request You to change the password or
          we may suspend Your account without any liability to electromart, for
          such period of time as we deem appropriate in the circumstances. We
          shall not be liable for any loss or damage arising from Your failure
          to comply with this provision.
        </p>
        <p>
          You will have access to other apps owned by electromart group
          companies through the same login username and password. You agree to
          have single login access to all the apps owned by electromart group
          companies.
        </p>
        <h6>Communications</h6>
        <p>
          When You use the Platform or send emails or other data, information or
          communication to us, You agree and understand that You are
          communicating with Us through electronic records and You consent to
          receive communications via electronic records from Us periodically and
          as and when required. We may communicate with you by email or by such
          other mode of communication, electronic or otherwise.
        </p>
        <h6>Platform for Transaction and Communication</h6>
        <p>
          The Platform enables the Buyer and Seller to transact on the Platform.
          electromart is not and cannot be a party to or control in any manner
          any transaction between the Platform's Users.
        </p>
        <h6>Henceforward:</h6>
        <li>
          All commercial/contractual terms are offered by and agreed to between
          Buyers and Sellers alone. The commercial/contractual terms include
          without limitation price, shipping costs, payment methods, payment
          terms, date, period and mode of delivery, warranties related to
          products and services and after sales services related to products and
          services. electromart does not have any control or does not determine
          or advise or in any way involve itself in the offering or acceptance
          of such commercial/contractual terms between the Buyers and Sellers.
          All discounts, offers (including exchange offers) are by the
          Seller/Brand and not by electromart.
        </li>
        <li>
          Placement of order by a Buyer with Seller on the Platform is an offer
          to buy the product(s) in by the Buyer to the Seller and it shall not
          be construed as Seller's acceptance of Buyer's offer to buy the
          product(s) ordered. The Seller retains the right to cancel any such
          order placed by the Buyer, at its sole discretion and the Buyer shall
          be intimated of the same by way of an email/SMS. Any transaction price
          paid by Buyer in case of such cancellation by Seller, shall be
          refunded to the Buyer. Further, the Seller may cancel an order wherein
          the quantities exceed the typical individual consumption. This applies
          both to the number of products ordered within a single order and the
          placing of several orders for the same product where the individual
          orders comprise a quantity that exceeds the typical individual
          consumption. What comprises a typical individual's consumption
          quantity limit shall be based on various factors and at the sole
          discretion of the Seller and may vary from individual to individual.
        </li>
        <li>
          electromart does not make any representation or Warranty as to
          specifics (such as quality, value, salability, etc) of the products or
          services proposed to be sold or offered to be sold or purchased on the
          Platform. electromart does not implicitly or explicitly support or
          endorse the sale or purchase of any products or services on the
          Platform. electromart accepts no liability for any errors or
          omissions, whether on behalf of itself or third parties.
        </li>
        <li>
          electromart is not responsible for any non-performance or breach of
          any contract entered into between Buyers and Sellers. electromart
          cannot and does not guarantee that the concerned Buyers and/or Sellers
          will perform any transaction concluded on the Platform. electromart
          shall not and is not required to mediate or resolve any dispute or
          disagreement between Buyers and Sellers.
        </li>
        <li>
          electromart does not make any representation or warranty as to the
          item-specifics (such as legal title, creditworthiness, identity, etc)
          of any of its Users. You are advised to independently verify the bona
          fides of any particular User that You choose to deal with on the
          Platform and use Your best judgment in that behalf.
        </li>
        <li>
          electromart does not at any point of time during any transaction
          between Buyer and Seller on the Platform come into or take possession
          of any of the products or services offered by Seller nor does it at
          any point gain title to or have any rights or claims over the products
          or services offered by Seller to Buyer.
        </li>
        <li>
          At no time shall electromart hold any right, title or interest over
          the products nor shall electromart have any obligations or liabilities
          in respect of such contract entered into between Buyers and Sellers.
          electromart is not responsible for unsatisfactory or delayed
          performance of services or damages or delays as a result of products
          which are out of stock, unavailable or back ordered.
        </li>
        <li>
          The Platform is only a platform that can be utilized by Users to reach
          a larger base to buy and sell products or services. electromart is
          only providing a platform for communication and it is agreed that the
          contract for sale of any of the products or services shall be a
          strictly bipartite contract between the Seller and the Buyer.
        </li>
        <p>
          At no time shall electromart hold any right, title or interest over
          the products nor shall electromart have any obligations or liabilities
          in respect of such contract.
        </p>
        <p>
          electromart is not responsible for unsatisfactory or delayed
          performance of services or damages or delays as a result of products
          which are out of stock, unavailable or back ordered.
        </p>
        <h6>
          Select products offered by sellers may be eligible for business
          purchases on the Platform.
        </h6>
        <li>
          Upon Your purchase of product(s) eligible for business purchases, You
          may be able to avail the benefits of GST input tax credit.
          Accordingly, at your request, an invoice containing the GSTIN as
          provided by You ("Tax Invoice") shall be issued to You by the
          Seller(s) selling such products.
        </li>
        <br />
        <p>
          * GST invoice will have, inter alia, the following details printed on
          it: -GSTIN associated with your registered business, as provided by
          you
        </p>
        <p>* Entity name of your registered business, as provided by you </p>
        <p>
          * Not all products are eligible for business purchases on the Platform
          and the same is solely at the discretion of the Sellers. You will be
          able to view the eligibility of Tax Invoice on the product page on the
          Platform.
        </p>
        <p>
          * Purchases on the Platform must only be for end consumption. Users
          must not use products purchased on the Platform for any commercial,
          promotional, resale or further distribution purposes.
        </p>
        <p>
          * For seamless availment of input tax credit, kindly mention the
          delivery address as the address which is mentioned as the registered
          place of business as per the records of GST authority. Please note
          that availment of input tax credit is subject to provisions of GST Act
          and rules.
        </p>
        <p>
          * The delivery and billing addresses will be required to be the same,
          please note that input tax credit will be denied by GST authority if
          the delivery address and GSTIN in the GST invoice are of different
          states.
        </p>
        <p>
          * If GSTIN and/or business entity details are not provided by You, it
          will be presumed that it is a personal purchase and not a business
          purchase.
        </p>
        <p>
          * electromart is not responsible to verify the correctness of the
          GSTIN and/or entity name provided by You and You shall be entirely
          responsible to provide the accurate details.
        </p>
        <p>
          * electromart and Seller shall not entertain any request for any
          revision in the GST Invoice. electromart and Seller shall not be
          liable for Your default including for reasons associated with details
          provided by You.
        </p>
        <p>
          * electromart will not be liable in case You are not able to avail
          input tax credit or if input tax credit is denied to You for any
          reason whatsoever.
        </p>
        <p>
          * You shall be solely liable for all compliances required under
          applicable laws.
        </p>
        <p>
          * You agree to indemnify and hold electromart and Seller harmless from
          all losses, claims, costs, expenses, suits, proceedings, or any other
          liability including any third-party claims (including any penalties
          imposed by governmental authorities) arising out of or in connection
          with (1) the GSTIN and/or entity name provided by you or the input tax
          credit claimed by you or your use or misuse of the GST Invoice and (2)
          your non-compliance with the applicable laws or (3) your use or misuse
          of any third-party’s details including GSTIN.
        </p>
        <p>
          * electromart has the right to not allow business purchases on the
          Platform to You if a fraudulent activity is identified.
        </p>
        <p>
          * Seller reserves the right to not issue Tax Invoice or issue a credit
          note against an already issued Tax Invoice to cancel the transaction,
          if any fraudulent activity is identified.
        </p>
        <li>
          You shall independently agree upon the manner and terms and conditions
          of delivery, payment, insurance etc. with the seller(s) that You
          transact with.
        </li>
        <p>
          Disclaimer: Pricing on any product(s) as is reflected on the Platform
          may due to some technical issue, typographical error or product
          information published by seller may be incorrectly reflected and in
          such an event seller may cancel such your order(s).
        </p>
        <li>
          You release and indemnify electromart and/or any of its officers and
          representatives from any cost, damage, liability or other consequence
          of any of the actions of the Users of the Platform and specifically
          waive any claims that you may have in this behalf under any applicable
          law. Notwithstanding its reasonable efforts in that behalf,
          electromart cannot take responsibility or control the information
          provided by other Users which is made available on the Platform. You
          may find other User's information to be offensive, harmful,
          inconsistent, inaccurate, or deceptive. Please use caution and
          practice safe trading when using the Platform.
        </li>
        <p>
          Please note that there could be risks in dealing with underage persons
          or people acting under false pretense.
        </p>
        <h6>Charges</h6>
        <p>
          electromart may charge a nominal fee for browsing and buying on the
          Platform. electromart reserves the right to change its Fee Policy from
          time to time. In particular, electromart may at its sole discretion
          introduce new services/fees and modify some or all of the existing
          services/fees offered on the Platform. In such an event, electromart
          reserves the right to introduce fees for the new services offered or
          amend/introduce fees for existing/new services, as the case may be.
          Changes to the Fee Policy shall be posted on the Platform and such
          changes shall automatically become effective immediately after they
          are posted on the Platform. Unless otherwise stated, all fees shall be
          quoted in Indian Rupees. You shall be solely responsible for
          compliance of all applicable laws including those in India for making
          payments to electromart Internet Private Limited.
        </p>
        <p>What is the platform fee?</p>
        <p>
          Fee levied by electromart to sustain the efficient operations and
          continuous improvement of the platform, for a hassle-free app
          experience.
        </p>
        <p>Refund of Platform Fee</p>
        <p>
          a) If the order is lost or undelivered to the preferred location, the
          complete order amount will be refunded if paid online, including the
          platform fee.
        </p>
        <p>
          b) If a customer cancels an order partially or returns part of an
          order, platform charges will be refunded as allocated to the item
          being returned/canceled.
        </p>
        <p>
          c) Platform charges will be refunded in case of a full order
          cancellation
        </p>
        <h6>Terms & Conditions:</h6>
        <p>
          * electromart Foundation is a Section 8 company registered under the
          Companies Act 2013.
        </p>
        <p>
          * The amount received as donation will be donated to NGOs and similar
          charitable organizations working in the selected thematic areas. You
          can visit www.electromartfoundation.org to know more about this.
        </p>
        <p>* The contribution, once made, will not be refunded.</p>
        <p>
          * No certificate under section 80G of the Income Tax Act, 1961 will be
          issued.
        </p>
        <p>
          * By proceeding to donate, you understand and confirm that this
          donation is not from any foreign source as defined under Foreign
          Contribution (Regulation) Act, 2010.
        </p>
        <p>
          * electromart Foundation disclaims any and all liability and assumes
          no responsibility whatsoever for consequences resulting from any
          actions or inactions of the NGOs or charitable organizations.
        </p>
        <p>
          * By proceeding to donate the money, you consent and expressly waive
          any and all claims, rights of action and/or remedies (under law or
          otherwise) that you may have against any of the electromart Group
          entities arising out of or in connection with the aforesaid
          transaction.
        </p>
        <p>
          * The donation is being collected on behalf of the electromart
          Foundation and is disbursed to electromart Foundation. electromart
          Internet Pvt Ltd disclaims all liabilities and assumes no
          responsibility for consequences resulting from actions/ inactions of
          the electromart Foundation.
        </p>
        <p>
          * electromart Internet Pvt. Ltd may share your Personal Identifiable
          Information which may include your name, phone number, etc with
          electromart Foundation.
        </p>
        <h6>Contents Posted on Platform</h6>
        <p>
          All text, graphics, user interfaces, visual interfaces, photographs,
          trademarks, logos, sounds, music and artwork (collectively,
          "Content"), is a third party user generated content and electromart
          has no control over such third party user generated content as
          electromart is merely an intermediary for the purposes of this Terms
          of Use.
        </p>
        <p>
          Except as expressly provided in these Terms of Use, no part of the
          Platform and no Content may be copied, reproduced, republished,
          uploaded, posted, publicly displayed, encoded, translated, transmitted
          or distributed in any way (including "mirroring") to any other
          computer, server, Platform or other medium for publication or
          distribution or for any commercial enterprise, without electromart's
          express prior written consent.
        </p>
        <p>
          You may use information on the products and services purposely made
          available on the Platform for downloading, provided that You: (1) do
          not remove any proprietary notice language in all copies of such
          documents, (2) use such information only for your personal,
          non-commercial informational purpose and do not copy or post such
          information on any networked computer or broadcast it in any media,
          (3) make no modifications to any such information, and (4) do not make
          any additional representations or warranties relating to such
          documents.
        </p>
        <p>
          You shall be responsible for any notes, messages, emails, reviews,
          ratings, billboard postings, photos, drawings, profiles, opinions,
          ideas, images, videos, audio files or other materials or information
          posted or transmitted to the Platform (collectively, "Content"). Such
          Content will become Our property and You grant Us the worldwide,
          perpetual and transferable rights in such Content. We shall be
          entitled to, consistent with Our Privacy Policy as adopted in
          accordance with applicable law, use the Content or any of its elements
          for any type of use forever, including but not limited to promotional
          and advertising purposes and in any media whether now known or
          hereafter devised, including the creation of derivative works that may
          include the Content You provide. You agree that any Content You post
          may be used by us, consistent with Our Privacy Policy and Rules of
          Conduct on Site as mentioned herein, and You are not entitled to any
          payment or other compensation for such use.
        </p>
        <p>
          SOME CONTENT OFFERED ON THE PLATFORM MAY NOT BE SUITABLE FOR SOME
          VIEWERS AND THEREFORE VIEWER DISCRETION IS ADVISED. ALSO, SOME CONTENT
          OFFERED ON THE PLATFORM MAY NOT BE APPROPRIATE FOR VIEWERSHIP BY
          CHILDREN. PARENTS AND/OR LEGAL GUARDIANS ARE ADVISED TO EXERCISE
          DISCRETION BEFORE ALLOWING THEIR CHILDREN AND/OR WARDS TO ACCESS
          CONTENT ON THE PLATFORM.
        </p>
        <h6>Privacy</h6>
        <p>
          We view protection of Your privacy as a very important principle. We
          understand clearly that You and Your Personal Information is one of
          Our most important assets. We store and process Your Information
          including any sensitive financial information collected (as defined
          under the Information Technology Act, 2000), if any, on computers that
          may be protected by physical as well as reasonable technological
          security measures and procedures in accordance with Information
          Technology Act 2000 and Rules there under. Our current Privacy Policy
          is available at Privacy. if You object to Your Information being
          transferred or used in this way please do not use the Platform.
        </p>
        <p>
          We may share personal information with our other corporate entities
          and affiliates. These entities and affiliates may market to you as a
          result of such sharing unless you explicitly opt-out.
        </p>
        <p>
          We may disclose personal information to third parties. This disclosure
          may be required for us to provide you access to our Services, to
          comply with our legal obligations, to enforce our User Agreement, to
          facilitate our marketing and advertising activities, or to prevent,
          detect, mitigate, and investigate fraudulent or illegal activities
          related to our Services. We do not disclose your personal information
          to third parties for their marketing and advertising purposes without
          your explicit consent.
        </p>
        <p>
          We may disclose personal information if required to do so by law or in
          the good faith belief that such disclosure is reasonably necessary to
          respond to subpoenas, court orders, or other legal process. We may
          disclose personal information to law enforcement offices, third party
          rights owners, or others in the good faith belief that such disclosure
          is reasonably necessary to: enforce our Terms or Privacy Policy;
          respond to claims that an advertisement, posting or other content
          violates the rights of a third party; or protect the rights, property
          or personal safety of our users or the general public.
        </p>
        <p>
          We and our affiliates will share / sell some or all of your personal
          information with another business entity should we (or our assets)
          plan to merge with, or be acquired by that business entity, or
          re-organization, amalgamation, restructuring of business. Should such
          a transaction occur that other business entity (or the new combined
          entity) will be required to follow this privacy policy with respect to
          your personal information.
        </p>
        <h6>Disclaimer of Warranties and Liability</h6>
        <p>
          This Platform, all the materials and products (including but not
          limited to software) and services, included on or otherwise made
          available to You through this site are provided on "as is" and "as
          available" basis without any representation or warranties, express or
          implied except otherwise specified in writing. Without prejudice to
          the forgoing paragraph, electromart does not warrant that:
        </p>
        <p>
          This Platform will be constantly available, or available at all; or
        </p>
        <p>
          The information on this Platform is complete, true, accurate or
          non-misleading.
        </p>
        <p>
          electromart will not be liable to You in any way or in relation to the
          Contents of, or use of, or otherwise in connection with, the Platform.
          electromart does not warrant that this site; information, Content,
          materials, product (including software) or services included on or
          otherwise made available to You through the Platform; their servers;
          or electronic communication sent from Us are free of viruses or other
          harmful components.
        </p>
        <p>
          Nothing on Platform constitutes, or is meant to constitute, advice of
          any kind. All the Products sold on Platform are governed by different
          state laws and if Seller is unable to deliver such Products due to
          implications of different state laws, Seller will return or will give
          credit for the amount (if any) received in advance by Seller from the
          sale of such Product that could not be delivered to You.
        </p>
        <p>
          You will be required to enter a valid phone number while placing an
          order on the Platform. By registering Your phone number with us, You
          consent to be contacted by Us via phone calls, SMS notifications,
          mobile applications and/or any other electronic mode of communication
          in case of any order or shipment or delivery related updates.
        </p>
        <h6>Services</h6>
        <h6>Order Fulfillment</h6>
        <p>
          Your purchases on the Platform include fulfillment and delivery
          services. Upon order confirmation, the Company will aim to facilitate
          delivery of your products within the timeframe communicated through
          the Platform. While we strive to provide accurate estimated delivery
          times, these may vary based on factors including third-party delivery
          partner availability, order volume, traffic conditions, weather, and
          unforeseen circumstances. We/Company will not be held liable for any
          delay in delivery of the Order.
        </p>
        <p>
          For your convenience, the estimated time of arrival (ETA) is displayed
          on the App's homepage before placing an order, allowing you to make
          informed purchasing decisions.
        </p>
        <p>
          Please be aware that additional delivery fees may apply based on
          factors such as severe weather, peak hours, high demand periods,
          late-night deliveries, packing and handling, platform maintenance, or
          small order fulfillment. These fees will be transparently displayed in
          the "Basket" section before place the order.
        </p>
        <h6>Payment</h6>
        <p>
          While availing any of the payment method/s available on the Platform,
          we will not be responsible or assume any liability, whatsoever in
          respect of any loss or damage arising directly or indirectly to You
          due to:
        </p>
        <li>Lack of authorization for any transaction/s, or</li>
        <li>
          Exceeding the preset limit mutually agreed by You and between
          "Bank/s", or
        </li>
        <li>Any payment issues arising out of the transaction, or</li>
        <li>Decline of transaction for any other reason/s</li>
        <p>
          All payments made against the purchases/services on Platform by you
          shall be compulsorily in Indian Rupees acceptable in the Republic of
          India. Platform will not facilitate transaction with respect to any
          other form of currency with respect to the purchases made on Platform.
        </p>
        <p>
          Before shipping / delivering your order to you, Seller may request you
          to provide supporting documents (including but not limited to Govt.
          issued ID and address proof) to establish the ownership of the payment
          instrument used by you for your purchase. This is done in the interest
          of providing a safe online shopping environment to Our Users.
        </p>
        <h6>Further:</h6>
        <li>
          Transactions, Transaction Price and all commercial terms such as
          Delivery, Dispatch of products and/or services are as per principal to
          principal bipartite contractual obligations between Buyer and Seller
          and payment facility is merely used by the Buyer and Seller to
          facilitate the completion of the Transaction. Use of the payment
          facility shall not render electromart liable or responsible for the
          non-delivery, non-receipt, non-payment, damage, breach of
          representations and warranties, non-provision of after sales or
          warranty services or fraud as regards the products and /or services
          listed on electromart's Platform.
        </li>
        <li>
          You have specifically authorized electromart or its service providers
          to collect, process, facilitate and remit payments and / or the
          Transaction Price electronically or through Cash on Delivery to and
          from other Users in respect of transactions through Payment Facility.
          Your relationship with electromart is on a principal to principal
          basis and by accepting these Terms of Use you agree that electromart
          is an independent contractor for all purposes, and does not have
          control of or liability for the products or services that are listed
          on electromart's Platform that are paid for by using the Payment
          Facility. electromart does not guarantee the identity of any User nor
          does it ensure that a Buyer or a Seller will complete a transaction.
        </li>
        <li>
          You understand, accept and agree that the payment facility provided by
          electromart is neither a banking nor financial service but is merely a
          facilitator providing an electronic, automated online electronic
          payment, receiving payment through Cash-on delivery, collection and
          remittance facility for the Transactions on the electromart Platform
          using the existing authorized banking infrastructure and Credit Card
          payment gateway networks. Further, by providing Payment Facility,
          electromart is neither acting as trustees nor acting in a fiduciary
          capacity with respect to the Transaction or the Transaction Price.
        </li>
        <h6>Payment Facility for Buyers:</h6>
        <li>
          You, as a Buyer, understand that upon initiating a Transaction You are
          entering into a legally binding and enforceable contract with the
          Seller to purchase the products and /or services from the Seller using
          the Payment Facility, and You shall pay the Transaction Price through
          Your Issuing Bank to the Seller using Payment Facility.
        </li>
        <li>
          You, as a Buyer, may agree with the Seller through electronic
          communication and electronic records and using the automated features
          as may be provided by Payment Facility on any extension / increase in
          the Dispatch and/or Delivery time and the Transaction shall stand
          amended to such extent. Any such extension / increase of Dispatch /
          Delivery time or subsequent novation / variation of the Transaction
          should be in compliance with Payment Facility Rules and Policies.
        </li>
        <li>
          You, as a Buyer, shall electronically notify Payment Facility using
          the appropriate electromart Platform features immediately upon
          Delivery or non- Delivery within the time period as provided in
          Policies. Non notification by You of Delivery or non- Delivery within
          the time period specified in the Policies shall be construed as a
          deemed Delivery in respect of that Transaction. In case of Cash- On
          Delivery transactions, Buyer is not required to confirm the receipt of
          products or services.
        </li>
        <li>
          You, as a Buyer, shall be entitled to claim a refund of the
          Transaction Price (as Your sole and exclusive remedy) in case You do
          not receive the Delivery within the time period agreed in the
          Transaction or within the time period as provided in the Policies,
          whichever is earlier. In case you do not raise a refund claim using
          Platform features within the stipulated time than this would make You
          ineligible for a refund.
        </li>
        <li>
          You, as a Buyer, understand that the Payment Facility may not be
          available in full or in part for certain category of products and/or
          services and/or Transactions as mentioned in the Policies and hence
          You may not be entitled to a refund in respect of the Transactions for
          those products and /or services
        </li>
        <li>
          Except for Cash On Delivery transaction, refund, if any, shall be made
          at the same Issuing Bank from where Transaction Price was received, or
          through any other method available on the Platform, as chosen by You.
        </li>
        <li>
          For Cash On Delivery transactions, refunds, if any, will be made via
          electronic payment transfers.
        </li>
        <li>
          Refund shall be made in Indian Rupees only and shall be equivalent to
          the Transaction Price received in Indian Rupees.
        </li>
        <li>
          For electronics payments, refund shall be made through payment
          facility using NEFT / RTGS or any other online banking / electronic
          funds transfer system approved by Reserve Bank India (RBI).
        </li>
        <li>
          Refunds may be supported for select banks. Where a bank is not
          supported for processing refunds, You will be required to share
          alternate bank account details with us for processing the refund.
        </li>
        <li>
          Refund shall be conditional and shall be with recourse available to
          electromart in case of any misuse by Buyer.
        </li>
        <li>
          We may also request you for additional documents for verification.
        </li>
        <li>Refund shall be subject to Buyer complying with Policies.</li>
        <li>
          electromart reserves the right to impose limits on the number of
          Transactions or Transaction Price which electromart may receive from
          on an individual Valid Credit/Debit/ Cash Card / Valid Bank Account/
          and such other infrastructure or any other financial instrument
          directly or indirectly through payment aggregator or through any such
          facility authorized by Reserve Bank of India to provide enabling
          support facility for collection and remittance of payment or by an
          individual Buyer during any time period, and reserves the right to
          refuse to process Transactions exceeding such limit.
        </li>
        <li>
          electromart reserves the right to refuse to process Transactions by
          Buyers with a prior history of questionable charges including without
          limitation breach of any agreements by Buyer with electromart or
          breach/violation of any law or any charges imposed by Issuing Bank or
          breach of any policy.
        </li>
        <li>
          electromart may do such checks as it deems fit before approving the
          receipt of/Buyers commitment to pay (for Cash On Delivery
          transactions) Transaction Price from the Buyer for security or other
          reasons at the discretion of electromart. As a result of such check if
          electromart is not satisfied with the creditability of the Buyer or
          genuineness of the Transaction or other reasons at its sole
          discretion, electromart shall have the right to reject the receipt of
          / Buyers commitment to pay Transaction Price. For avoidance of doubt,
          it is hereby clarified that the ‘Cash on Delivery’ feature for
          payment, may be disabled for certain account users, at the sole
          discretion of electromart.
        </li>
        <li>
          electromart may delay notifying the payment confirmation i.e.
          informing Seller to dispatch, if electromart deems suspicious or for
          Buyers conducting high transaction volumes to ensure safety of the
          Transaction and Transaction Price. In addition, electromart may hold
          Transaction Price and electromart may not inform Seller to Dispatch or
          remit Transaction Price to law enforcement officials (instead of
          refunding the same to Buyer) at the request of law enforcement
          officials or in the event the Buyer is engaged in any form of illegal
          activity.
        </li>
        <li>
          The Buyer and Seller acknowledge that electromart will not be liable
          for any damages, interests or claims etc. resulting from not
          processing a Transaction/Transaction Price or any delay in processing
          a Transaction/Transaction Price which is beyond control of
          electromart.
        </li>
        <h6>Compliance with Laws:</h6>
        <li>
          As required by applicable law, if the Customer makes a purchase of an
          amount equal to or above INR 2, 00, 000.00/- the Customer will be
          required to upload a scanned copy of his/her PAN card on the Platform,
          within 4 days of making the purchase, failing which, the purchase made
          by the Customer will be cancelled. The requirement to submit the PAN
          card arises only once and if it has been submitted already by the
          Customer, it need not be submitted again. The order of the Customer
          shall stand cancelled if there is a discrepancy between the name of
          the Customer and the name on the PAN Card.
        </li>
        <li>
          Buyer and Seller shall comply with all the applicable laws (including
          without limitation Foreign Exchange Management Act, 1999 and the rules
          made and notifications issued there under and the Exchange Control
          Manual as may be issued by Reserve Bank of India from time to time,
          Customs Act, Information and Technology Act, 2000 as amended by the
          Information Technology (Amendment) Act 2008, Prevention of Money
          Laundering Act, 2002 and the rules made there under, Foreign
          Contribution Regulation Act, 1976 and the rules made there under,
          Income Tax Act, 1961 and the rules made there under, Export Import
          Policy of government of India) applicable to them respectively for
          using Payment Facility and electromart Platform.
        </li>
        <h6>Buyer's arrangement with Issuing Bank:</h6>
        <li>
          All valid Credit / Debit/ Cash Card/ and other payment instruments are
          processed using a Credit Card payment gateway or appropriate payment
          system infrastructure and the same will also be governed by the terms
          and conditions agreed between the Buyer and the respective Issuing
          Bank and payment instrument issuing company.
        </li>
        <li>
          All Online Bank Transfers from Valid Bank Accounts are processed using
          the gateway provided by the respective Issuing Bank which support
          Payment Facility to provide these services to the Users. All such
          Online Bank Transfers on Payment Facility are also governed by the
          terms and conditions agreed to between Buyer and the respective
          Issuing Bank.
        </li>
        <h6>Contacting the Seller</h6>
        <p>
          At electromart we are committed towards ensuring that disputes between
          sellers and buyers are settled amicably by way of the above dispute
          resolution mechanisms and procedures. However, in the event that a
          buyer wishes to contact the seller, he/ she may proceed to do so by
          accessing the seller related information made available by the sellers
          on their product listing pages. Alternatively, the buyers may also
          reach out to customer support at 044-45614700 or access help center at
          https://www.electromart.com/helpcentre.
        </p>
      </div>
    </>
  );
};
export default Termsofuse;
